name: 'server'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync python3 ca-certificates

      - name: Test server
        run: |
          python3 -m unittest tests/*.py
